### ISSUE TITLE
php error on invalid url

### ISSUE THREAD

**Issue by JBinggi** [OnePlc/PLC_X_Core#11]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.12

#### Summary

If you will access a invalid url, you get a php Error

#### Current behavior

 Trying to get property 'oUser' of non-object in module/Application/view/layout/layout-default.phtmlon line 74

#### How to reproduce
Trying to access any unvalid url on the.
for example your_one_place/updatee

#### Expected behavior
Redirect to home or an error page

**Comment by Praesidiarius** [comment]
fixed in master-dev will be released with 1.0.13. error pages now have own layouts. currently its a minimalistic layout, which will produce no further errors. new issue created to style the page.
