### ISSUE TITLE
class ZipArchive not found

### ISSUE THREAD

**Issue by JBinggi** [OnePlc/PLC_X_Core#12]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.x

#### Summary

if you want to upload a custom theme the, it drops a php Error

#### Current behavior
upload a themes.zip results in an error: 
class 'ZipArchive' not found

#### How to reproduce
On a fresh core installation with go under /application/themes and try to upload a themes.zip
Only php7* installed

#### Expected behavior
Show a errorpage with â link to dokumentation to fix this issue

**Comment by Praesidiarius** [comment]
done from 1.0.12 onwards
