### ISSUE TITLE
Fix buggy /update

### ISSUE THREAD

**Issue by JBinggi** [OnePlc/PLC_X_Core#18]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.x

#### Summary
/update is bubby with multiple module

#### Current behavior
If you install multiple module and at the same time you get an sql_error
Also Module outside of the package oneplace can not be installed.

#### How to reproduce
Install a new core with multiple module an go to /update

#### Expected behavior
Detect new module an install them correctly, execute install.sql properly.

**Comment by Praesidiarius** [comment]
new setup in 1.0.19
