### ISSUE TITLE
multiselect broken

### ISSUE THREAD

**Issue by JBinggi** [OnePlc/PLC_X_Core#20]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.21

#### Summary
Multiselect is broken

#### Current behavior
Cant save multiple items, 

#### How to reproduce
install article or contact module and try to save more then 1 entry

#### Expected behavior
Multipe new inserts should work

**Comment by Praesidiarius** [comment]
use tag name as fieldkey to make add work
